spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itmanager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false # 关闭Thymeleaf缓存
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      zzgs:
        springbootdemo:
          mapper: debug